// ── Curated AI Model Catalogue ──────────────────────────────────────────────
// Hand-researched (2026-04-29) registry of leading models across the three
// roles the app supports: prompt assistant (text), image, and animation.
// Each entry has a verified billing URL, an explicit api-availability flag,
// and a current integration status. The Search UI reads this directly.
//
// Adding a new entry:
// 1. Set `verifiedAt` to today's date.
// 2. Verify the billingUrl manually.
// 3. Mark `integrationStatus` honestly — `native` only if our backend already
//    speaks this provider's API. Otherwise `coming-soon` / `via-replicate` /
//    `preview-only` / `no-api`.

import type { AIRole } from "./aiRoles";

export type IntegrationStatus =
  | "native"        // our backend already routes to this model live
  | "via-replicate" // accessible via the existing Replicate integration
  | "preview-only"  // listed in UI but routes through fallback (Phase B)
  | "coming-soon"   // catalogued but not addable yet
  | "no-api";       // provider does not offer a public API

export interface CatalogueEntry {
  id: string;
  label: string;
  role: AIRole;
  provider: string;
  providerKey?: "openai" | "replicate" | "runway" | "imagineart" | "anthropic" | "google" | "deepseek" | "mistral" | "midjourney" | "adobe" | "luma" | "pika" | "stability";
  description: string;
  pricing: string;
  homepageUrl: string;
  billingUrl: string;
  apiKeysUrl?: string;
  apiAvailable: boolean;
  publiclyAvailable: boolean;
  integrationStatus: IntegrationStatus;
  incompatibilityReason?: string;
  popularity: number;       // 0-100, used as default sort
  tags: string[];
  verifiedAt: string;       // ISO date — when entry was last manually checked
  badge?: string;
  apiModel?: string;        // model id sent to the SDK for native integrations
}

export const AI_CATALOGUE: CatalogueEntry[] = [
  // ── Prompt Assistant ──────────────────────────────────────────────────────
  {
    id: "openai-gpt-4o-mini",
    label: "GPT-4o-mini",
    role: "prompt",
    provider: "OpenAI",
    providerKey: "openai",
    apiModel: "gpt-4o-mini",
    description: "Fast, cheap, strong prompt assistant. App default.",
    pricing: "~$0.15 / 1M input · ~$0.60 / 1M output",
    homepageUrl: "https://openai.com/api/",
    billingUrl: "https://platform.openai.com/settings/organization/billing/overview",
    apiKeysUrl: "https://platform.openai.com/api-keys",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "native",
    popularity: 95,
    tags: ["openai", "gpt", "fast", "cheap", "default"],
    verifiedAt: "2026-04-29",
    badge: "Default",
  },
  {
    id: "openai-gpt-4o",
    label: "GPT-4o",
    role: "prompt",
    provider: "OpenAI",
    providerKey: "openai",
    apiModel: "gpt-4o",
    description: "Premium OpenAI tier. Stronger reasoning + creative writing.",
    pricing: "~$2.50 / 1M input · ~$10 / 1M output",
    homepageUrl: "https://openai.com/api/",
    billingUrl: "https://platform.openai.com/settings/organization/billing/overview",
    apiKeysUrl: "https://platform.openai.com/api-keys",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "native",
    popularity: 90,
    tags: ["openai", "gpt", "premium", "reasoning"],
    verifiedAt: "2026-04-29",
    badge: "Premium",
  },
  {
    id: "openai-o1-preview",
    label: "OpenAI o1-preview",
    role: "prompt",
    provider: "OpenAI",
    providerKey: "openai",
    apiModel: "o1-preview",
    description: "Reasoning-tuned model — slower but stronger at planning, math, complex briefs.",
    pricing: "~$15 / 1M input · ~$60 / 1M output",
    homepageUrl: "https://openai.com/api/",
    billingUrl: "https://platform.openai.com/settings/organization/billing/overview",
    apiKeysUrl: "https://platform.openai.com/api-keys",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "native",
    popularity: 70,
    tags: ["openai", "reasoning", "premium", "slow", "thinking"],
    verifiedAt: "2026-04-29",
    badge: "Reasoning",
  },
  {
    id: "anthropic-claude-haiku",
    label: "Claude 3.5 Haiku",
    role: "prompt",
    provider: "Anthropic",
    providerKey: "anthropic",
    apiModel: "claude-3-5-haiku-20241022",
    description: "Fast Claude tier — good speed/quality balance.",
    pricing: "~$0.80 / 1M input · ~$4 / 1M output",
    homepageUrl: "https://www.anthropic.com/api",
    billingUrl: "https://console.anthropic.com/settings/billing",
    apiKeysUrl: "https://console.anthropic.com/settings/keys",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "preview-only",
    popularity: 88,
    tags: ["anthropic", "claude", "fast"],
    verifiedAt: "2026-04-29",
    badge: "Phase B preview",
  },
  {
    id: "anthropic-claude-sonnet",
    label: "Claude 4 Sonnet",
    role: "prompt",
    provider: "Anthropic",
    providerKey: "anthropic",
    apiModel: "claude-sonnet-4",
    description: "Anthropic's flagship balanced model. Strong creative writing + coding.",
    pricing: "~$3 / 1M input · ~$15 / 1M output",
    homepageUrl: "https://www.anthropic.com/api",
    billingUrl: "https://console.anthropic.com/settings/billing",
    apiKeysUrl: "https://console.anthropic.com/settings/keys",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "preview-only",
    popularity: 92,
    tags: ["anthropic", "claude", "premium", "creative"],
    verifiedAt: "2026-04-29",
    badge: "Phase B preview",
  },
  {
    id: "google-gemini-flash",
    label: "Gemini 2.0 Flash",
    role: "prompt",
    provider: "Google",
    providerKey: "google",
    apiModel: "gemini-2.0-flash",
    description: "Has a generous FREE tier — great escape hatch when other providers hit quota.",
    pricing: "free tier · paid ~$0.075 / 1M input",
    homepageUrl: "https://ai.google.dev/",
    billingUrl: "https://aistudio.google.com/app/apikey",
    apiKeysUrl: "https://aistudio.google.com/app/apikey",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "preview-only",
    popularity: 85,
    tags: ["google", "gemini", "free-tier", "fast", "cheap"],
    verifiedAt: "2026-04-29",
    badge: "Free tier",
  },
  {
    id: "deepseek-v3",
    label: "DeepSeek V3",
    role: "prompt",
    provider: "DeepSeek",
    providerKey: "deepseek",
    apiModel: "deepseek-chat",
    description: "Open-weights model with a paid API. Very cheap; competitive on most reasoning tasks.",
    pricing: "~$0.27 / 1M input · ~$1.10 / 1M output",
    homepageUrl: "https://platform.deepseek.com/",
    billingUrl: "https://platform.deepseek.com/top_up",
    apiKeysUrl: "https://platform.deepseek.com/api_keys",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "coming-soon",
    popularity: 78,
    tags: ["deepseek", "cheap", "open"],
    verifiedAt: "2026-04-29",
    badge: "Cheap",
  },
  {
    id: "mistral-large",
    label: "Mistral Large 2",
    role: "prompt",
    provider: "Mistral AI",
    providerKey: "mistral",
    apiModel: "mistral-large-latest",
    description: "European-hosted model with strong multilingual + coding performance.",
    pricing: "~$2 / 1M input · ~$6 / 1M output",
    homepageUrl: "https://mistral.ai/",
    billingUrl: "https://console.mistral.ai/billing/",
    apiKeysUrl: "https://console.mistral.ai/api-keys/",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "coming-soon",
    popularity: 72,
    tags: ["mistral", "european", "multilingual"],
    verifiedAt: "2026-04-29",
  },

  // ── Image Generator ───────────────────────────────────────────────────────
  {
    id: "openai-gpt-image-1",
    label: "GPT-Image-1",
    role: "image",
    provider: "OpenAI",
    providerKey: "openai",
    apiModel: "gpt-image-1",
    description: "Strongest prompt adherence + native edit support. App default.",
    pricing: "~$0.19 / img (high · 1024²)",
    homepageUrl: "https://openai.com/api/",
    billingUrl: "https://platform.openai.com/settings/organization/billing/overview",
    apiKeysUrl: "https://platform.openai.com/api-keys",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "native",
    popularity: 95,
    tags: ["openai", "image", "ui-text", "icons", "default"],
    verifiedAt: "2026-04-29",
    badge: "Default",
  },
  {
    id: "openai-dalle-3",
    label: "DALL-E 3",
    role: "image",
    provider: "OpenAI",
    providerKey: "openai",
    apiModel: "dall-e-3",
    description: "OpenAI's previous-gen image model. Still strong for stylised illustration.",
    pricing: "~$0.04–0.12 / img",
    homepageUrl: "https://openai.com/api/",
    billingUrl: "https://platform.openai.com/settings/organization/billing/overview",
    apiKeysUrl: "https://platform.openai.com/api-keys",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "native",
    popularity: 80,
    tags: ["openai", "dalle", "image", "illustration"],
    verifiedAt: "2026-04-29",
  },
  {
    id: "replicate-flux-1.1-ultra",
    label: "FLUX 1.1 Pro Ultra",
    role: "image",
    provider: "Black Forest Labs (via Replicate)",
    providerKey: "replicate",
    apiModel: "black-forest-labs/flux-1.1-pro-ultra",
    description: "Top-tier detail and texture — hero backgrounds & premium symbols.",
    pricing: "~$0.06 / img",
    homepageUrl: "https://blackforestlabs.ai/",
    billingUrl: "https://replicate.com/account/billing",
    apiKeysUrl: "https://replicate.com/account/api-tokens",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "native",
    popularity: 92,
    tags: ["flux", "bfl", "image", "premium", "ultra"],
    verifiedAt: "2026-04-29",
    badge: "Ultra",
  },
  {
    id: "replicate-flux-schnell",
    label: "FLUX Schnell",
    role: "image",
    provider: "Black Forest Labs (via Replicate)",
    providerKey: "replicate",
    apiModel: "black-forest-labs/flux-schnell",
    description: "Fastest FLUX variant — 1-4 step inference. Great for quick iterations.",
    pricing: "~$0.003 / img",
    homepageUrl: "https://blackforestlabs.ai/",
    billingUrl: "https://replicate.com/account/billing",
    apiKeysUrl: "https://replicate.com/account/api-tokens",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "via-replicate",
    popularity: 86,
    tags: ["flux", "fast", "cheap", "schnell"],
    verifiedAt: "2026-04-29",
    badge: "Fast",
  },
  {
    id: "imagineart-flux-ultra",
    label: "FLUX 1.1 Pro Ultra (Imagine Art)",
    role: "image",
    provider: "Imagine Art / Vyro AI",
    providerKey: "imagineart",
    apiModel: "vyro-flux-1.1-pro-ultra",
    description: "Same FLUX Ultra, different host. 1500 free credits on signup.",
    pricing: "credit-based (~$0.04–$0.08 / img)",
    homepageUrl: "https://www.imagine.art/api",
    billingUrl: "https://platform.imagine.art/",
    apiKeysUrl: "https://platform.imagine.art/",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "native",
    popularity: 75,
    tags: ["flux", "imagine-art", "vyro", "free-credits"],
    verifiedAt: "2026-04-29",
    badge: "1500 free credits",
  },
  {
    id: "replicate-sd-3.5",
    label: "Stable Diffusion 3.5 Large",
    role: "image",
    provider: "Stability AI (via Replicate)",
    providerKey: "replicate",
    apiModel: "stability-ai/stable-diffusion-3.5-large",
    description: "Best composition & cinematic lighting — ideal for layered backgrounds.",
    pricing: "~$0.065 / img",
    homepageUrl: "https://stability.ai/",
    billingUrl: "https://replicate.com/account/billing",
    apiKeysUrl: "https://replicate.com/account/api-tokens",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "native",
    popularity: 84,
    tags: ["stability", "sd", "stable-diffusion", "cinematic"],
    verifiedAt: "2026-04-29",
  },
  {
    id: "replicate-ideogram-v3",
    label: "Ideogram v3",
    role: "image",
    provider: "Ideogram (via Replicate)",
    providerKey: "replicate",
    description: "Best-in-class typography rendering — generates accurate text in images.",
    pricing: "~$0.08 / img",
    homepageUrl: "https://ideogram.ai/",
    billingUrl: "https://replicate.com/account/billing",
    apiKeysUrl: "https://replicate.com/account/api-tokens",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "via-replicate",
    popularity: 78,
    tags: ["ideogram", "text", "typography", "logo"],
    verifiedAt: "2026-04-29",
    badge: "Best for text",
  },
  {
    id: "replicate-recraft-v3",
    label: "Recraft v3",
    role: "image",
    provider: "Recraft (via Replicate)",
    providerKey: "replicate",
    description: "Vector + raster brand asset generator. Strong for logos and icon sets.",
    pricing: "~$0.04 / img",
    homepageUrl: "https://www.recraft.ai/",
    billingUrl: "https://replicate.com/account/billing",
    apiKeysUrl: "https://replicate.com/account/api-tokens",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "via-replicate",
    popularity: 72,
    tags: ["recraft", "vector", "logo", "brand"],
    verifiedAt: "2026-04-29",
  },
  {
    id: "midjourney",
    label: "Midjourney v6",
    role: "image",
    provider: "Midjourney",
    description: "Premier artistic image model — but only accessible via Discord/web app.",
    pricing: "$10–60/mo subscription, no API",
    homepageUrl: "https://www.midjourney.com/",
    billingUrl: "https://www.midjourney.com/account/",
    apiAvailable: false,
    publiclyAvailable: true,
    integrationStatus: "no-api",
    incompatibilityReason: "Midjourney does not offer a public API. Generation is gated to their Discord bot and web app — there's no programmatic access we can integrate. Excellent model, just not addable here.",
    popularity: 88,
    tags: ["midjourney", "artistic", "premium", "no-api"],
    verifiedAt: "2026-04-29",
  },
  {
    id: "adobe-firefly",
    label: "Adobe Firefly Image 3",
    role: "image",
    provider: "Adobe",
    providerKey: "adobe",
    description: "Adobe's generative image model. Has a Firefly API but it's gated to Creative Cloud Enterprise customers only.",
    pricing: "Enterprise-only · contact sales",
    homepageUrl: "https://www.adobe.com/products/firefly.html",
    billingUrl: "https://www.adobe.com/products/firefly/business.html",
    apiAvailable: true,
    publiclyAvailable: false,
    integrationStatus: "no-api",
    incompatibilityReason: "Adobe Firefly's API is gated to Creative Cloud Enterprise customers. Without an enterprise contract, individual API access isn't available.",
    popularity: 65,
    tags: ["adobe", "firefly", "enterprise", "gated"],
    verifiedAt: "2026-04-29",
  },
  {
    id: "google-imagen-3",
    label: "Google Imagen 3",
    role: "image",
    provider: "Google",
    providerKey: "google",
    description: "Google's photorealistic image model. API access via Vertex AI requires Google Cloud project + billing.",
    pricing: "~$0.04 / img on Vertex AI",
    homepageUrl: "https://deepmind.google/technologies/imagen-3/",
    billingUrl: "https://console.cloud.google.com/billing",
    apiKeysUrl: "https://console.cloud.google.com/apis/credentials",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "coming-soon",
    popularity: 80,
    tags: ["google", "imagen", "photorealistic", "vertex"],
    verifiedAt: "2026-04-29",
  },

  // ── Animation Generator ───────────────────────────────────────────────────
  {
    id: "runway-gen3-alpha",
    label: "Runway Gen-3 Alpha",
    role: "animation",
    provider: "Runway",
    providerKey: "runway",
    apiModel: "runway-gen3",
    description: "Cinematic 10–16s clips — slot intros, jackpot reveals, parallax loops.",
    pricing: "~$0.05 / sec (~$0.50 / 10s)",
    homepageUrl: "https://runwayml.com/",
    billingUrl: "https://dev.runwayml.com/",
    apiKeysUrl: "https://dev.runwayml.com/",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "native",
    popularity: 92,
    tags: ["runway", "video", "cinematic"],
    verifiedAt: "2026-04-29",
    badge: "Default",
  },
  {
    id: "runway-gen3-turbo",
    label: "Runway Gen-3 Alpha Turbo",
    role: "animation",
    provider: "Runway",
    providerKey: "runway",
    description: "Faster, cheaper Runway tier — good for iteration. Use Gen-3 Alpha for finals.",
    pricing: "~$0.025 / sec (~$0.25 / 10s)",
    homepageUrl: "https://runwayml.com/",
    billingUrl: "https://dev.runwayml.com/",
    apiKeysUrl: "https://dev.runwayml.com/",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "coming-soon",
    popularity: 80,
    tags: ["runway", "video", "fast"],
    verifiedAt: "2026-04-29",
    badge: "Fast",
  },
  {
    id: "luma-dream-machine",
    label: "Luma Dream Machine (Ray-2)",
    role: "animation",
    provider: "Luma AI",
    providerKey: "luma",
    description: "Smooth 5–9s motion loops — ambient parallax backgrounds, looping FX.",
    pricing: "~$0.40 / 5s (720p)",
    homepageUrl: "https://lumalabs.ai/",
    billingUrl: "https://lumalabs.ai/dream-machine/api",
    apiKeysUrl: "https://lumalabs.ai/dream-machine/api/keys",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "coming-soon",
    popularity: 80,
    tags: ["luma", "video", "loops", "parallax"],
    verifiedAt: "2026-04-29",
  },
  {
    id: "replicate-kling",
    label: "Kling 2.1 Master",
    role: "animation",
    provider: "Kuaishou (via Replicate)",
    providerKey: "replicate",
    apiModel: "kwaivgi/kling-v2.1-master",
    description: "Strong character & symbol animation — wild splash, scatter activation FX.",
    pricing: "~$1.30 / 5s (1080p)",
    homepageUrl: "https://klingai.com/",
    billingUrl: "https://replicate.com/account/billing",
    apiKeysUrl: "https://replicate.com/account/api-tokens",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "via-replicate",
    popularity: 78,
    tags: ["kling", "kuaishou", "character", "video"],
    verifiedAt: "2026-04-29",
  },
  {
    id: "stability-svd",
    label: "Stable Video Diffusion",
    role: "animation",
    provider: "Stability AI (via Replicate)",
    providerKey: "replicate",
    description: "Open-weights short video clips. Good for ambient loops.",
    pricing: "~$0.05 / video",
    homepageUrl: "https://stability.ai/stable-video",
    billingUrl: "https://replicate.com/account/billing",
    apiKeysUrl: "https://replicate.com/account/api-tokens",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "via-replicate",
    popularity: 72,
    tags: ["stability", "svd", "video", "open"],
    verifiedAt: "2026-04-29",
  },
  {
    id: "pika-1.5",
    label: "Pika 1.5",
    role: "animation",
    provider: "Pika Labs",
    providerKey: "pika",
    description: "Fluid character motion + scene transitions. Strong creative video model.",
    pricing: "subscription · no public API",
    homepageUrl: "https://pika.art/",
    billingUrl: "https://pika.art/account",
    apiAvailable: false,
    publiclyAvailable: true,
    integrationStatus: "no-api",
    incompatibilityReason: "Pika does not currently expose a public API. Generation is only available via their web app. Watch their developer page for a future API release.",
    popularity: 84,
    tags: ["pika", "video", "no-api"],
    verifiedAt: "2026-04-29",
  },
  // ── Layered Assets ────────────────────────────────────────────────────────
  {
    id: "recraft-v3-layered",
    label: "Recraft v3 — Layered output",
    role: "layered",
    provider: "Recraft (via Replicate)",
    providerKey: "replicate",
    description: "Vector + raster brand assets — useful as a layered-asset source. Layer extraction is a Phase B post-process step.",
    pricing: "~$0.04 / img",
    homepageUrl: "https://www.recraft.ai/",
    billingUrl: "https://replicate.com/account/billing",
    apiKeysUrl: "https://replicate.com/account/api-tokens",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "via-replicate",
    popularity: 75,
    tags: ["recraft", "layered", "vector", "raster"],
    verifiedAt: "2026-04-29",
    badge: "Phase B layer extract",
  },
  {
    id: "stability-layerdiffuse",
    label: "LayerDiffuse / IC-Light (research)",
    role: "layered",
    provider: "Open research (Stability-related)",
    description: "Research project enabling layered/transparent output and re-lighting from a 2D image. Not yet productized as a hosted API.",
    pricing: "self-host only",
    homepageUrl: "https://github.com/lllyasviel/LayerDiffuse",
    billingUrl: "https://github.com/lllyasviel/LayerDiffuse",
    apiAvailable: false,
    publiclyAvailable: true,
    integrationStatus: "no-api",
    incompatibilityReason: "LayerDiffuse / IC-Light are open-source research projects without a hosted API. To use, you'd self-host the weights on your own GPU server.",
    popularity: 65,
    tags: ["layerdiffuse", "ic-light", "layered", "research", "open-source"],
    verifiedAt: "2026-04-29",
    badge: "Research",
  },
  {
    id: "layered-coming-soon",
    label: "Coming soon — multi-layer slot art",
    role: "layered",
    provider: "Roadmap",
    description: "We're tracking a hosted layered-output service. When one ships with a public API, it'll auto-appear in this catalogue.",
    pricing: "TBD",
    homepageUrl: "https://github.com/lllyasviel/LayerDiffuse",
    billingUrl: "https://github.com/lllyasviel/LayerDiffuse",
    apiAvailable: false,
    publiclyAvailable: false,
    integrationStatus: "coming-soon",
    incompatibilityReason: "No leading hosted layered-asset service is live yet. We'll add native support as soon as one launches with a public API.",
    popularity: 60,
    tags: ["coming-soon", "layered"],
    verifiedAt: "2026-04-29",
    badge: "Coming soon",
  },

  // ── Rigging & Mocap ───────────────────────────────────────────────────────
  {
    id: "mixamo",
    label: "Mixamo (Adobe)",
    role: "rigging",
    provider: "Adobe",
    description: "Auto-rigs FBX/OBJ characters and applies a free animation library. Web app only — no public API for programmatic use.",
    pricing: "Free with Adobe ID",
    homepageUrl: "https://www.mixamo.com/",
    billingUrl: "https://www.mixamo.com/",
    apiAvailable: false,
    publiclyAvailable: true,
    integrationStatus: "no-api",
    incompatibilityReason: "Mixamo is a web-only auto-rigging tool by Adobe. No public API for programmatic integration. Use it manually: upload FBX → download rigged + animated FBX.",
    popularity: 88,
    tags: ["mixamo", "adobe", "rigging", "auto-rig", "no-api"],
    verifiedAt: "2026-04-29",
  },
  {
    id: "cascadeur",
    label: "Cascadeur",
    role: "rigging",
    provider: "Nekki",
    description: "AI-assisted physics-based animation desktop app — secondary motion, balance, posing assist. No API.",
    pricing: "Free indie / paid pro",
    homepageUrl: "https://cascadeur.com/",
    billingUrl: "https://cascadeur.com/buy",
    apiAvailable: false,
    publiclyAvailable: true,
    integrationStatus: "no-api",
    incompatibilityReason: "Cascadeur is a desktop animation app — no API surface. Use it standalone for character animation work.",
    popularity: 78,
    tags: ["cascadeur", "animation", "desktop", "no-api"],
    verifiedAt: "2026-04-29",
  },
  {
    id: "moveai",
    label: "Move.ai",
    role: "rigging",
    provider: "Move AI",
    description: "Markerless mocap from regular video. Has an API for studios doing automated mocap pipelines.",
    pricing: "subscription · contact for API access",
    homepageUrl: "https://www.move.ai/",
    billingUrl: "https://www.move.ai/pricing",
    apiKeysUrl: "https://www.move.ai/contact",
    apiAvailable: true,
    publiclyAvailable: false,
    integrationStatus: "no-api",
    incompatibilityReason: "Move.ai exposes an API but only to enterprise customers via direct outreach. Without an enterprise contract we can't integrate.",
    popularity: 80,
    tags: ["moveai", "mocap", "video", "enterprise"],
    verifiedAt: "2026-04-29",
  },
  {
    id: "plask-motion",
    label: "Plask Motion",
    role: "rigging",
    provider: "Plask",
    description: "Browser-based AI mocap from video — extracts skeletal animation. Has an API.",
    pricing: "free trial · paid tiers",
    homepageUrl: "https://plask.ai/",
    billingUrl: "https://plask.ai/pricing",
    apiKeysUrl: "https://plask.ai/dashboard",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "coming-soon",
    popularity: 72,
    tags: ["plask", "mocap", "browser"],
    verifiedAt: "2026-04-29",
  },
  {
    id: "deepmotion-animate3d",
    label: "DeepMotion Animate 3D",
    role: "rigging",
    provider: "DeepMotion",
    description: "Mocap from video → glTF/FBX/BVH animation. Has a documented API for paid tiers.",
    pricing: "$12+/mo · paid API",
    homepageUrl: "https://www.deepmotion.com/animate-3d",
    billingUrl: "https://www.deepmotion.com/pricing",
    apiKeysUrl: "https://app.deepmotion.com/account/api",
    apiAvailable: true,
    publiclyAvailable: true,
    integrationStatus: "coming-soon",
    popularity: 78,
    tags: ["deepmotion", "mocap", "animate3d"],
    verifiedAt: "2026-04-29",
    badge: "Has API",
  },

  {
    id: "openai-sora",
    label: "OpenAI Sora",
    role: "animation",
    provider: "OpenAI",
    providerKey: "openai",
    description: "OpenAI's flagship video model. Currently in private preview — no public API.",
    pricing: "TBD when public",
    homepageUrl: "https://openai.com/sora",
    billingUrl: "https://platform.openai.com/",
    apiAvailable: false,
    publiclyAvailable: false,
    integrationStatus: "preview-only",
    incompatibilityReason: "Sora is in private preview. OpenAI hasn't released a public API yet — once they do, we'll wire it up automatically.",
    popularity: 95,
    tags: ["openai", "sora", "video", "preview"],
    verifiedAt: "2026-04-29",
    badge: "Private preview",
  },
];

export function searchCatalogue(query: string, opts?: { role?: AIRole; addedIds?: string[]; limit?: number }): CatalogueEntry[] {
  const q       = query.trim().toLowerCase();
  const role    = opts?.role;
  const skip    = new Set(opts?.addedIds ?? []);
  const limit   = opts?.limit ?? 12;

  let pool = AI_CATALOGUE.filter((e) => !skip.has(e.id));
  if (role) pool = pool.filter((e) => e.role === role);

  if (!q) {
    return pool.sort((a, b) => b.popularity - a.popularity).slice(0, limit);
  }

  const tokens = q.split(/\s+/).filter(Boolean);
  const scored = pool
    .map((e) => {
      const haystack = [
        e.label.toLowerCase(),
        e.provider.toLowerCase(),
        e.description.toLowerCase(),
        ...(e.tags ?? []),
      ].join(" ");
      let score = 0;
      for (const t of tokens) {
        if (haystack.includes(t)) score += 10;
        if (e.label.toLowerCase().includes(t)) score += 25; // label match weighted higher
        if (e.tags?.some((tag) => tag === t)) score += 20;  // exact tag match
      }
      return { entry: e, score };
    })
    .filter((s) => s.score > 0)
    .sort((a, b) => (b.score - a.score) || (b.entry.popularity - a.entry.popularity))
    .slice(0, limit)
    .map((s) => s.entry);

  return scored;
}

export function getCatalogueEntry(id: string): CatalogueEntry | null {
  return AI_CATALOGUE.find((e) => e.id === id) ?? null;
}

export function isAddable(e: CatalogueEntry): { ok: true } | { ok: false; reason: string } {
  if (!e.apiAvailable) return { ok: false, reason: e.incompatibilityReason ?? "This model does not expose a public API." };
  if (!e.publiclyAvailable) return { ok: false, reason: e.incompatibilityReason ?? "This model is in private preview / waitlist — public API access isn't open yet." };
  return { ok: true };
}
