import type { BuildCategoryDef } from "@/app/types/build";

export const BOARD_GAME: BuildCategoryDef = {
  slug: "board-game",
  label: "Board Game",
  short: "Board",
  icon: "🎲",
  tagline: "Tabletop, cards, miniatures",
  description: "Generate a print-ready board-game asset pack — board, cards, tokens, dice, packaging.",
  estimatedAssetCount: 9,

  steps: [
    {
      id: "identity",
      title: "Game identity",
      questions: [
        { id: "title",        type: "text",  label: "Game title",  placeholder: "e.g. Crystal Caverns", required: true, maxLength: 60 },
        { id: "genre",        type: "radio", label: "Genre",       required: true,
          options: [
            { value: "strategy",       label: "Strategy" },
            { value: "party",          label: "Party" },
            { value: "family",         label: "Family" },
            { value: "kids",           label: "Kids" },
            { value: "co-op",          label: "Cooperative" },
            { value: "eurogame",       label: "Euro / point-salad" },
            { value: "wargame",        label: "Wargame" },
            { value: "trivia",         label: "Trivia / quiz" },
            { value: "roll-and-write", label: "Roll-and-write" },
          ],
        },
        { id: "playerCount",  type: "radio", label: "Player count",  required: true,
          options: [
            { value: "1",   label: "1 (Solo)" },
            { value: "2",   label: "2" },
            { value: "3-4", label: "3–4" },
            { value: "5-8", label: "5–8" },
            { value: "8+",  label: "8+" },
          ],
        },
        { id: "ageRange",     type: "radio", label: "Target age",    required: true,
          options: [
            { value: "6+",  label: "6+" },
            { value: "8+",  label: "8+" },
            { value: "10+", label: "10+" },
            { value: "12+", label: "12+" },
            { value: "14+", label: "14+" },
            { value: "18+", label: "18+" },
          ],
        },
      ],
    },
    {
      id: "theme",
      title: "Theme & narrative",
      questions: [
        { id: "theme",      type: "radio", label: "Theme", required: true,
          options: [
            { value: "fantasy",     label: "Fantasy" },
            { value: "sci-fi",      label: "Sci-fi" },
            { value: "historical",  label: "Historical" },
            { value: "modern",      label: "Modern" },
            { value: "abstract",    label: "Abstract" },
            { value: "animals",     label: "Animals" },
            { value: "nature",      label: "Nature" },
            { value: "horror",      label: "Horror" },
            { value: "mythology",   label: "Mythology" },
          ],
        },
        { id: "length",     type: "radio", label: "Game length", required: true,
          options: [
            { value: "<30",   label: "Under 30 min" },
            { value: "30-60", label: "30–60 min" },
            { value: "60-90", label: "60–90 min" },
            { value: "90+",   label: "90+ min" },
          ],
        },
        { id: "complexity", type: "radio", label: "Complexity", required: true,
          options: [
            { value: "light",  label: "Light",  description: "Easy to teach, no rules-lawyering" },
            { value: "medium", label: "Medium", description: "Strategic but accessible" },
            { value: "heavy",  label: "Heavy",  description: "Deep, long rulebook" },
          ],
        },
        { id: "setting",    type: "longtext", label: "Setting / world (free text)", placeholder: "e.g. Underground crystal caves with bioluminescent rivers and ancient ruins", maxLength: 400, rows: 3, required: true },
      ],
    },
    {
      id: "art",
      title: "Art direction",
      questions: [
        { id: "artStyle",       type: "radio", label: "Art style", required: true,
          options: [
            { value: "cartoon",    label: "Cartoon" },
            { value: "painterly",  label: "Painterly" },
            { value: "pixel",      label: "Pixel art" },
            { value: "vector",     label: "Vector / flat" },
            { value: "realistic",  label: "Realistic" },
            { value: "folk-art",   label: "Folk art" },
            { value: "watercolor", label: "Watercolor" },
          ],
        },
        { id: "palette",        type: "radio", label: "Color palette", required: true,
          options: [
            { value: "vivid",      label: "Vivid" },
            { value: "muted",      label: "Muted" },
            { value: "monochrome", label: "Monochrome" },
            { value: "pastel",     label: "Pastel" },
            { value: "bold",       label: "Bold" },
            { value: "earthy",     label: "Earthy" },
            { value: "neon",       label: "Neon" },
          ],
        },
        { id: "mood",           type: "radio", label: "Mood",
          options: [
            { value: "triumphant", label: "Triumphant" },
            { value: "mysterious", label: "Mysterious" },
            { value: "whimsical",  label: "Whimsical" },
            { value: "serious",    label: "Serious" },
            { value: "playful",    label: "Playful" },
            { value: "dark",       label: "Dark" },
          ],
        },
        { id: "inspiration",    type: "longtext", label: "Inspiration", placeholder: "Name games or art you're inspired by — Catan, Wingspan, Studio Ghibli, etc.", maxLength: 300, rows: 2 },
      ],
    },
    {
      id: "components",
      title: "Components",
      questions: [
        { id: "components",     type: "multi-select", label: "Required components", required: true, min: 1,
          options: [
            { value: "board",         label: "Game board" },
            { value: "cards",         label: "Cards" },
            { value: "tokens",        label: "Tokens" },
            { value: "dice",          label: "Dice" },
            { value: "miniatures",    label: "Miniatures" },
            { value: "tiles",         label: "Tiles" },
            { value: "spinner",       label: "Spinner" },
            { value: "money",         label: "Money / currency" },
            { value: "playerBoards",  label: "Player boards" },
            { value: "sandTimer",     label: "Sand timer" },
          ],
        },
        { id: "boardLayout",    type: "radio", label: "Board layout",
          options: [
            { value: "grid",       label: "Grid" },
            { value: "hex",        label: "Hex" },
            { value: "path",       label: "Path / track" },
            { value: "modular",    label: "Modular tiles" },
            { value: "open-world", label: "Open / map-style" },
          ],
        },
        { id: "cardCount",      type: "number", label: "Number of cards (total deck)", min: 0, max: 500, step: 5, suffix: "cards" },
        { id: "uniquePieces",   type: "number", label: "Number of unique piece types", min: 0, max: 100, step: 1 },
      ],
    },
    {
      id: "specs",
      title: "Production specs",
      subtitle: "These drive print-ready dimensions",
      questions: [
        { id: "cardSize",   type: "radio", label: "Card dimensions",
          options: [
            { value: "poker",  label: "Poker (2.5×3.5″)" },
            { value: "bridge", label: "Bridge (2.25×3.5″)" },
            { value: "mini",   label: "Mini (1.75×2.5″)" },
            { value: "tarot",  label: "Tarot (2.75×4.75″)" },
            { value: "custom", label: "Custom" },
          ],
        },
        { id: "boardSize",  type: "radio", label: "Board size",
          options: [
            { value: "small",  label: "Small (14×14″)" },
            { value: "medium", label: "Medium (17×17″)" },
            { value: "large",  label: "Large (20×20″)" },
            { value: "custom", label: "Custom" },
          ],
        },
        { id: "tokenShape", type: "radio", label: "Token shape",
          options: [
            { value: "round",        label: "Round disc" },
            { value: "square",       label: "Square chip" },
            { value: "custom-shape", label: "Custom-shape" },
            { value: "meeple",       label: "Meeple" },
          ],
        },
        { id: "boxSize",    type: "radio", label: "Box size",
          options: [
            { value: "small",  label: "Small (8×8″)" },
            { value: "medium", label: "Medium (11×11″)" },
            { value: "large",  label: "Large (12×12″)" },
          ],
        },
      ],
    },
    {
      id: "branding",
      title: "Branding & references",
      questions: [
        { id: "titleTreatment", type: "radio", label: "Game-title visual treatment",
          options: [
            { value: "bold-sans",      label: "Bold sans-serif" },
            { value: "hand-drawn",     label: "Hand-drawn" },
            { value: "vintage-serif",  label: "Vintage serif" },
            { value: "modern-minimal", label: "Modern minimal" },
            { value: "distressed",     label: "Distressed / weathered" },
          ],
        },
        { id: "brandKeywords",  type: "text",     label: "Brand keywords",      placeholder: "epic, mystical, family-friendly", maxLength: 200 },
        { id: "avoid",          type: "longtext", label: "What to avoid",       placeholder: "e.g. no skulls, no horror imagery, no realistic blood", maxLength: 300, rows: 2 },
        { id: "edition",        type: "text",     label: "Edition / version note (optional)", placeholder: "First Edition · Halloween Special" },
        { id: "reference",      type: "file",     label: "Upload reference (PDF, image, prototype)", accept: ".pdf,image/*", maxBytes: 10 * 1024 * 1024 },
        { id: "referenceUrl",   type: "url",      label: "Or paste a reference URL", placeholder: "https://…" },
      ],
    },
  ],

  assets: [
    { id: "board",          label: "Game board",            group: "Board",      width: 2400, height: 2400, format: "png", dpi: 300, notes: "Print-ready 8″ at 300dpi (resize for actual board size)" },
    { id: "card-front",     label: "Card front (sample)",   group: "Cards",      width: 750,  height: 1050, format: "png", dpi: 300, notes: "Poker dimensions 2.5×3.5″ at 300dpi with 0.125″ bleed" },
    { id: "card-back",      label: "Card back",             group: "Cards",      width: 750,  height: 1050, format: "png", dpi: 300, notes: "Uniform across deck" },
    { id: "tokens",         label: "Token set sheet",       group: "Components", width: 1024, height: 1024, format: "png", notes: "Grid of 6-9 token variants on transparent background" },
    { id: "dice",           label: "Dice faces sheet",      group: "Components", width: 1024, height: 1024, format: "png", notes: "Six faces of a custom die laid out 2×3" },
    { id: "box-top",        label: "Box top",               group: "Packaging",  width: 1500, height: 1500, format: "png", dpi: 300, notes: "Square box top — title, art, age rating" },
    { id: "box-side",       label: "Box side panel",        group: "Packaging",  width: 1500, height: 600,  format: "png", dpi: 300 },
    { id: "rulebook-cover", label: "Rulebook cover",        group: "Packaging",  width: 2550, height: 3300, format: "png", dpi: 300, notes: "8.5×11″ at 300dpi" },
    { id: "player-board",   label: "Player board",          group: "Components", width: 2100, height: 1500, format: "png", dpi: 300, notes: "Per-player surface — track resources, score, role" },
  ],
};
