import type { BuildCategoryDef } from "@/app/types/build";

export const UTILITY_APP: BuildCategoryDef = {
  slug: "utility-app",
  label: "Utility App",
  short: "Utility",
  icon: "🛠️",
  tagline: "Productivity, dashboards, internal tools",
  description: "Generate a full asset pack for a productivity / business / utility application — app icons, launch screens, screen mockups, illustrations.",
  estimatedAssetCount: 12,

  steps: [
    {
      id: "identity",
      title: "Identity",
      subtitle: "Tell us what we're building",
      questions: [
        { id: "appName",       type: "text",  label: "App name",                     placeholder: "e.g. Pulse Analytics", required: true, maxLength: 60 },
        { id: "industry",      type: "radio", label: "Industry / domain",            required: true,
          options: [
            { value: "finance",      label: "Finance" },
            { value: "healthcare",   label: "Healthcare" },
            { value: "education",    label: "Education" },
            { value: "retail",       label: "Retail / E-commerce" },
            { value: "saas",         label: "SaaS" },
            { value: "productivity", label: "Productivity" },
            { value: "social",       label: "Social" },
            { value: "travel",       label: "Travel" },
            { value: "logistics",    label: "Logistics" },
            { value: "other",        label: "Other" },
          ],
        },
        { id: "persona",       type: "radio", label: "Primary persona",              required: true,
          options: [
            { value: "admin",      label: "Admin",            description: "Internal operators, control panels" },
            { value: "end-user",   label: "End user",         description: "Day-to-day users of the product" },
            { value: "analyst",    label: "Data analyst",     description: "Reporting, dashboards, insights" },
            { value: "operations", label: "Operations",       description: "Workflow / fulfillment teams" },
            { value: "customer",   label: "Customer-facing",  description: "Public-facing experience" },
            { value: "developer",  label: "Developer",        description: "DevTools / APIs / consoles" },
          ],
        },
        { id: "coreFunction",  type: "longtext", label: "One-line description of the core function", placeholder: "e.g. Track team OKRs and weekly progress", required: true, maxLength: 240, rows: 2 },
      ],
    },
    {
      id: "platform",
      title: "Platform",
      subtitle: "Where will this run?",
      questions: [
        { id: "platforms",      type: "multi-select", label: "Target platforms", required: true, min: 1,
          options: [
            { value: "ios",         label: "iOS" },
            { value: "android",     label: "Android" },
            { value: "web",         label: "Web" },
            { value: "macos",       label: "macOS" },
            { value: "windows",     label: "Windows" },
          ],
        },
        { id: "formFactor",     type: "multi-select", label: "Form factor", required: true, min: 1,
          options: [
            { value: "phone",   label: "Phone" },
            { value: "tablet",  label: "Tablet" },
            { value: "desktop", label: "Desktop" },
            { value: "tv",      label: "TV" },
          ],
        },
        { id: "orientation",    type: "radio", label: "Default orientation", required: true,
          options: [
            { value: "portrait",  label: "Portrait" },
            { value: "landscape", label: "Landscape" },
            { value: "both",      label: "Both" },
          ],
        },
        { id: "minOsVersion",   type: "text",  label: "Minimum OS version (optional)", placeholder: "e.g. iOS 16, Android 10" },
      ],
    },
    {
      id: "design-system",
      title: "Design system",
      subtitle: "Set the visual language",
      questions: [
        { id: "visualStyle",    type: "radio", label: "Visual style", required: true,
          options: [
            { value: "minimal",      label: "Minimal",       description: "Clean, lots of whitespace" },
            { value: "material-you", label: "Material You",  description: "Google Material 3" },
            { value: "apple-hig",    label: "Apple HIG",     description: "Native-feeling iOS / macOS" },
            { value: "editorial",    label: "Editorial",     description: "Magazine-like typography" },
            { value: "playful",      label: "Playful",       description: "Bold, friendly, illustrated" },
            { value: "brutalist",    label: "Brutalist",     description: "Raw, blocky, high-contrast" },
            { value: "neumorphic",   label: "Neumorphic",    description: "Soft 3D embossed surfaces" },
          ],
        },
        { id: "colorTheme",     type: "radio", label: "Theme support", required: true,
          options: [
            { value: "light",         label: "Light only" },
            { value: "dark",          label: "Dark only" },
            { value: "both",          label: "Light + dark" },
            { value: "auto-adaptive", label: "Auto-adaptive (system)" },
          ],
        },
        { id: "primaryColor",   type: "color", label: "Primary brand color", required: true },
        { id: "typography",     type: "radio", label: "Typography style",
          options: [
            { value: "sans-serif", label: "Sans-serif" },
            { value: "serif",      label: "Serif" },
            { value: "display",    label: "Display / decorative" },
            { value: "custom",     label: "Custom" },
          ],
        },
      ],
    },
    {
      id: "components",
      title: "Components",
      subtitle: "What's in the app?",
      questions: [
        { id: "screens",        type: "multi-select", label: "Required screens", required: true, min: 1,
          options: [
            { value: "login",         label: "Login" },
            { value: "onboarding",    label: "Onboarding" },
            { value: "dashboard",     label: "Dashboard" },
            { value: "profile",       label: "Profile" },
            { value: "settings",      label: "Settings" },
            { value: "search",        label: "Search" },
            { value: "list",          label: "List view" },
            { value: "form",          label: "Form" },
            { value: "empty",         label: "Empty state" },
            { value: "error",         label: "Error state" },
            { value: "notifications", label: "Notifications" },
            { value: "subscription",  label: "Subscription / paywall" },
          ],
        },
        { id: "navigation",     type: "radio", label: "Navigation pattern", required: true,
          options: [
            { value: "tab-bar",    label: "Tab bar" },
            { value: "drawer",     label: "Side drawer" },
            { value: "bottom-nav", label: "Bottom nav" },
            { value: "top-nav",    label: "Top nav" },
            { value: "none",       label: "None / single screen" },
          ],
        },
        { id: "density",        type: "radio", label: "UI density", required: true,
          options: [
            { value: "compact",     label: "Compact" },
            { value: "comfortable", label: "Comfortable" },
            { value: "spacious",    label: "Spacious" },
          ],
        },
        { id: "iconography",    type: "radio", label: "Iconography",
          options: [
            { value: "outline",  label: "Outline" },
            { value: "filled",   label: "Filled" },
            { value: "two-tone", label: "Two-tone" },
            { value: "custom",   label: "Custom illustrated" },
          ],
        },
      ],
    },
    {
      id: "deliverables",
      title: "Deliverables",
      subtitle: "What should we generate?",
      questions: [
        { id: "appIcon",          type: "toggle", label: "App icon (1024² + adaptive variants)", defaultOn: true },
        { id: "launchScreen",     type: "toggle", label: "Launch / splash screens",              defaultOn: true },
        { id: "marketingCount",   type: "number", label: "Marketing screenshots",                min: 0, max: 8, step: 1, suffix: "shots" },
        { id: "notificationIcon", type: "toggle", label: "Notification icon (96² monochrome)" },
      ],
    },
    {
      id: "branding",
      title: "Branding & references",
      subtitle: "Final context for generation",
      questions: [
        { id: "brandKeywords",  type: "text",     label: "Brand keywords",       placeholder: "trustworthy, modern, data-first", maxLength: 200 },
        { id: "tone",           type: "radio",    label: "Tone of voice",
          options: [
            { value: "professional",  label: "Professional" },
            { value: "friendly",      label: "Friendly" },
            { value: "playful",       label: "Playful" },
            { value: "authoritative", label: "Authoritative" },
            { value: "casual",        label: "Casual" },
          ],
        },
        { id: "avoid",          type: "longtext", label: "What to avoid", placeholder: "e.g. no stock photos, no clip-art, no bright red", maxLength: 300, rows: 2 },
        { id: "reference",      type: "file",     label: "Upload reference (PDF, image, prototype screenshot)", accept: ".pdf,image/*", maxBytes: 10 * 1024 * 1024 },
        { id: "referenceUrl",   type: "url",      label: "Or paste a reference URL (Figma / Dribbble / live site)", placeholder: "https://…" },
      ],
    },
  ],

  // Production-ready asset spec. Dimensions matter — these are passed to the
  // prompt builder as render hints + post-process resize targets.
  assets: [
    { id: "icon-1024",      label: "App icon — primary",           group: "App icon",   width: 1024, height: 1024, format: "png", notes: "Square master, ready for App Store / play store" },
    { id: "icon-android",   label: "Adaptive icon (Android)",      group: "App icon",   width: 432,  height: 432,  format: "png", notes: "Foreground layer, safe zone 264×264 centred" },
    { id: "favicon-512",    label: "Favicon 512×512",              group: "App icon",   width: 512,  height: 512,  format: "png" },

    { id: "splash-ios",     label: "iOS launch screen",            group: "Launch",     width: 1170, height: 2532, format: "png", notes: "iPhone 13/14/15 portrait" },
    { id: "splash-android", label: "Android splash",               group: "Launch",     width: 1080, height: 1920, format: "png" },

    { id: "mockup-login",     label: "Login screen mockup",        group: "Mockups",    width: 1170, height: 2532, format: "png" },
    { id: "mockup-dashboard", label: "Dashboard mockup",           group: "Mockups",    width: 1170, height: 2532, format: "png" },
    { id: "mockup-settings",  label: "Settings mockup",            group: "Mockups",    width: 1170, height: 2532, format: "png" },

    { id: "illus-empty",   label: "Empty state illustration",      group: "Illustrations", width: 800, height: 600, format: "png" },
    { id: "illus-error",   label: "Error state illustration",      group: "Illustrations", width: 800, height: 600, format: "png" },

    { id: "onboarding-1",  label: "Onboarding screen 1",           group: "Onboarding", width: 1170, height: 2532, format: "png" },
    { id: "notif-icon",    label: "Notification icon (monochrome)", group: "Misc",      width: 96,   height: 96,   format: "png", notes: "Single-color, pure white silhouette on transparent" },
  ],
};
